GET localhost:8080/upload/wishlist

###
GET localhost:8080/upload/wishlist/+79811131773

###
GET localhost:8080/upload/wishlist/+79994754619

###
GET localhost:8080/upload/contacts

###
GET localhost:8080/upload/contacts/+79811131773

###
GET localhost:8080/upload/my_collection

###
GET localhost:8080/upload/my_collection/+79811131773

###
GET localhost:8080/upload/my_collection/+79816984956

###
GET localhost:8080/upload/my_collection/+79994754619


###
POST localhost:8080/upload/wishlist/
Content-Type: application/json

{
  "name" : "Camel Up",
  "profile" : "+79811131773"
}

###
GET localhost:8080/upload/profile

###
GET localhost:8080/upload/profile/+79811131773

###
GET localhost:8080/upload/profile/+79994754619

###
GET localhost:8080/upload/profile/+79816984956

###
POST localhost:8080/meetings/
Content-Type: application/json

{
  "date": "2024-07-20",
  "location": "New Holland",
  "boardgames": ["Bloodborne", "God of War"],
  "contacts": ["+79811131773"]
}

###
POST localhost:8080/meetings/2/invite
Content-Type: application/json

["+79811131773", "+79816984956"]

###
GET localhost:8080/meetings/2/invitations

###
POST localhost:8080/meetings/
