CREATE TABLE SPRING_SESSION
(
    PRIMARY_ID            VARCHAR(255) PRIMARY KEY,
    SESSION_ID            VARCHAR(255) NOT NULL,
    CREATION_TIME         BIGINT,
    LAST_ACCESS_TIME      BIGINT,
    MAX_INACTIVE_INTERVAL INT
);

CREATE TABLE SPRING_SESSION_ATTRIBUTES
(
    PRIMARY_ID      VARCHAR(255),
    ATTRIBUTE_NAME  VARCHAR(255),
    ATTRIBUTE_BYTES BLOB,
    CONSTRAINT FK_SPRING_SESSION_ATTRIBUTES_SPRING_SESSION FOREIGN KEY (PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID)
);
